# Generated by Django 4.2 on 2023-06-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='card',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
